### ISSUE TITLE
Kustomize plugin produces extra non-YAML output which prevents piping

### ISSUE THREAD

**Issue by larslevie** [mgoltzsche/khelm#10]
The Kustomize plugin produces a few lines of info/debug output at the top of its stdout. Example:

```
Running khelm 2.0.0-alpha.1-dev-b455984 (helm 3.4.1)
WARNING: using untrusted repository "https://helm.releases.hashicorp.com"
Downloading repository index of https://helm.releases.hashicorp.com
Downloading chart vault 0.8.0 from repo https://helm.releases.hashicorp.com
Rendering chart vault 0.8.0 with name "vault" and namespace "vault"
Rendering chart vault 0.8.0 with name "vault" and namespace "vault"
apiVersion: v1
kind: ServiceAccount
metadata:
```

Te first size line aren't valid YAML which prevents piping to `kubectl`, e.g. `kustomize build --enable-alpha-plugins path/to/kustomization | kubectl apply -f -`

Is there an option to disable this output, of some other approach to using khelm that isn't documented?

**Comment by larslevie** [comment]
My bad, I'm running kustomize from inside a Docker container and trying to pipe the output of the container to my local kubectl. Docker mixes stderr and stdout together, so that's my problem.

**Comment by mgoltzsche** [comment]
Yes, somehow the stderr ended up within stdout in your case. Though docker wouldn't do that by default.

Since you render your manifests within a container anyway I recommend to use a [kpt](https://github.com/GoogleContainerTools/kpt)-based workflow for which I also provided some [examples](https://github.com/mgoltzsche/khelm#kpt-function-usage-example) - actually these are kustomize functions since the kpt [function functionality](https://github.com/kubernetes-sigs/kustomize/tree/master/kyaml/fn) is maintained within the kustomize repository but kustomize itself doesn't use it yet. `kpt fn run .` streams manifests via stdin into a docker container that runs a function, receives its output via stdout and writes it to disk (where you could commit it to your git repo and apply GitOps practices and/or apply it to a cluster using either `kubectl apply .` or better `kpt live apply .` which also supports pruning).
This way you can also avoid dealing with a single bloated container image that contains all kinds of binaries (kustomize+khelm plugin+...) with different versions but instead have one image for each binary.

**Comment by larslevie** [comment]
Thanks for the suggestion. I've been meaning to look into `kpt`, and the approach of committing the output of the hydrated Helm file is attractive -- I prefer to have (some version of) the actual YAML manifests committed, as opposed to a complete abstraction.

**Comment by larslevie** [comment]
> Yes, somehow the stderr ended up within stdout in your case. Though docker wouldn't do that by default.

Technically it's running in a `docker-compose`-managed container, so  possibly that is different. I know that `docker logs` will mix stderr and stdout, so I guess it makes some sense. But like you said, I've never noticed it before.
