### ISSUE TITLE
[FEAT] Support reusing helm cache between runs

### ISSUE THREAD

**Issue by howardjohn** [mgoltzsche/khelm#15]
**Is your feature request related to a problem? Please describe.**
Currently, a run of the function takes about 5s on my machine. This isn't too bad, but adds up once a few repos are being expanded. Running with `kpt fn run --network .`.

A lot of this time seems to be on fetching and indexing helm repos. The helm binary has caching for these, which seems like it might be feasible to use here to speed things up

**Describe the solution you'd like**
It would be great to have caching for this. I tried mounting the host's cache (`--mount type=bind,src=$HOME/.cache/helm/,dst=/root/.cache/helm --mount type=bind,src=$HOME/.config/helm/,dst=/root/.config/helm`), but it looks like we create a custom temporary helm home: https://github.com/mgoltzsche/khelm/blob/3bad288c63c288c5600a63984b4d88b0a853f10b/pkg/helm/repositories.go#L351

**Comment by mgoltzsche** [comment]
@howardjohn thanks for reporting the issue!

Caching should work when you mount a host directory to `/helm` within the container (env var `HELM_HOME`).
Please let me know if that works for you.
I ll document this and add a test case.

**Comment by mgoltzsche** [comment]
@howardjohn I am closing this issue since it is [documented](https://github.com/mgoltzsche/khelm/commit/3eb087d0062fc6abf1f42524534f3b623e530e71) and [tested](https://github.com/mgoltzsche/khelm/commit/52c4bd5e85204a30f765d7a3a4c0ac937d0baa39) now (the fix that comes with the latter was only related to khelm 1/Helm 2).
In case something is still unclear feel free to open it again or create a new issue.

@arnaud-mey this was concerning you as well.

**Comment by howardjohn** [comment]
Awesome, thanks @mgoltzsche !  I just tested that out and works great
