### ISSUE TITLE
[FEAT] Native support for helm plugins

### ISSUE THREAD

**Issue by ndbrew** [mgoltzsche/khelm#31]
**Is your feature request related to a problem? Please describe.**
My GitOps workflow right now involves generating helm manifests and then patching them with kustomize. I consider the values file a secret due to the information it can expose and would like to use the helm secrets plugin to encrypt them. khelm doesn't depend on a local install of helm, so getting things to work for my use case isn't ideal.

**Describe the solution you'd like**
Add an optional flag to the `khelm template` command that takes a plugin url / plugin version that gets installed prior to rendering.
Add optional configuration to the ChartRenderer manifest to support the same inside kustomize

An added benefit for the argocd use case is that you could add/remove helm plugins without having to modify the argocd container image to place the binaries.

**Describe alternatives you've considered**
Currently the workaround is to install the plugins to the HELM_PLUGIN directory which is automatically loaded via the helm libraries. However doing so would either require manual installation of the plugin or installation of the helm binary. The latter could potentially be problematic if the statically linked version of helm in khelm differs from the locally installed binary.

**Additional context**
One drawback to this solution is that it would increase the execution time as each time you try and run the command it would download the plugin unless some kind of caching was implemented.

**Comment by mgoltzsche** [comment]
> Add optional configuration to the ChartRenderer manifest [to support specifying the plugins that should be downloaded/enabled]

Allowing users to declare plugins within the kustomize plugin configuration would be a potential security vulnerability since an attacker could make a kustomization download and execute any code. Therefore and because of the efficiency issue you mentioned I think khelm should not support downloading plugins dynamically on-the-fly.

Alternatively would it help you if khelm also supported the `helm plugin install` command? That would at least simplify the installation of new plugins without having to install a corresponding version of the `helm` binary.
A pull request would be welcome!

**Comment by ndbrew** [comment]
`helm plugin install` would work and still simplify the process to an extent.
I actually looked through some other plugins and many of them depend on external binaries or other features of helm. Due to this and the fact my images contain the helm binary anyway, I think I'm ok with manually installing the plugins.

I'll close this one out for now.
