### ISSUE TITLE
[QUESTION] Future of the kustomize exec plugin given their upcoming deprecation?

### ISSUE THREAD

**Issue by jskrzypek** [mgoltzsche/khelm#34]
The [current Kustomize docs](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_plugins/) say that the previous/existing plugin methods (via `--enable-alpha-plugins`) are going to be deprecated:
![Screen Shot 2022-06-24 at 3 24 02 PM](https://user-images.githubusercontent.com/1513265/175652559-a574a6fb-9001-4892-9cb5-13cb2cbaa00b.png)

Clicking through the links to [the kustomize plugins KEP PR](https://github.com/kubernetes/enhancements/issues/2953) and the [KEP itself](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2953-kustomize-plugin-graduation), it seems they intend the current plugin ecosystem to be replaced with [KRM-style functions](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md) (which it that mentions `kpt` also uses). 

@mgoltzsche Are you aware of these changes? Does the fact that `khelm` is also available as a `kpt` function mean that it is (in a way) already forward-compatible with the deprecation?

**Comment by jskrzypek** [comment]
Reading up a little more on the state of things in kustomize-land, it looks like the latest version of kustomize should already support the container version of the kpt function usage you describe if you pass `--enable-alpha-plugins`

**Comment by jskrzypek** [comment]
Hey I answered my question! Aside from the possibility of some QoL improvements to the API, this works with the new sort of invocation. I opened a PR with docs and an example: #35

**Comment by mgoltzsche** [comment]
@jskrzypek I wasn't aware that kustomize plugins are deprectated already but it makes sense to me, given that kustomize also supports KRM functions now.
The KRM function support that I've implemented and tested with an older kpt version could also work with kustomize indeed - I just haven't tested that.
However the KRM function specification changed recently so that declarative function containers are not allowed to use the file system or network which is why the khelm kept function approach documented in the readme of this repo doesn't work anymore - I have to update the readme. As I understand this is to enforce gitops best practices and for security reasons.
Fortunately you can still use khelm as imperative function, e.g. to write a helm chart's output into a kustomization directory and commit the result, whenever you update the chart dependency, practicing true gitops. For instance like [this](https://github.com/GoogleContainerTools/kpt/issues/2450#issuecomment-898961698). kustomize may provide a similar command - I haven't looked at that for a while but I will...

**Comment by jskrzypek** [comment]
So with modern kustomize at least (I think I tested on 4.5) you can get it to work with the --enable-alpha-plugins & --network flags to enable network access. I tested it with the example I provided in #35

**Comment by mgoltzsche** [comment]
Thanks for creating the PR. I am going to review it and play a bit with
modern kustomize in sunday.

Joshua Skrzypek ***@***.***> schrieb am Sa., 25. Juni 2022,
09:05:
