### ISSUE TITLE
helm v3 support plan ?

### ISSUE THREAD

**Issue by nxmatic** [mgoltzsche/khelm#9]
Do you have plan for supporting helm v3 ? It will be soon a blocker, as helm v2 is already deprecated (ie: https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan). 

I discovered your plugin today and used it with a chart not aligned on-to v3 specs. But, just after, while 
I was redoing the same for another, I've got the error. 

`khelm: apiVersion 'v2' is not valid. The value must be "v1"`

**Comment by mgoltzsche** [comment]
I am working on that - actually I am going to finish this next weekend. You could try the helm 3 version using my `helm3` branch but please don't fork it since I might amend it. The kustomize generator config there also requires `apiVersion: v2` - like helm's `Chart.yaml`. If you're more patient: I am going to release 1.0.0-beta (helm 2) and 2.0.0-beta (helm 3) next weekend after I improved the e2e tests, github workflows und updated the readme which is completely outdated in terms of the CLI, helm-to-kustomize conversion and kpt function capabilities khelm supports now as well.

**Comment by mgoltzsche** [comment]
I am closing this one since Helm 3 support is managed within the `v2` branch for now from which you could also fork.
I am going to move Helm 2 support into a `v1` branch and the `v2` branch into master soon.
GitHub workflows are set up and there's a `v2.0.0-alpha.1` release: the binary is attached to the release and the container image is hosted on both the DockerHub and GitHub registry. (Though to access the GitHub registry you need to authenticate.)
